services:
  # --- DATABASE ---
  db:
    image: postgres:17.10-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s
    volumes:
      - fs_pg_data:/var/lib/postgresql/data

  # --- BACKEND ---
  backend:
    container_name: backend
    build:
      context: .
    env_file:
      - .env
    environment:
      UVICORN_HOST: ${RUN__HOST}
      UVICORN_PORT: ${RUN__PORT}
      UVICORN_WORKERS: ${RUN__WORKERS}
    depends_on:
      db:
        condition: service_healthy

volumes:
  fs_pg_data:
