services:
  # --- DATABASE ---
  db:
    image: postgres:17.10-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s
    volumes:
      - pg_data:/var/lib/postgresql/data

  # --- BACKEND ---
  backend:
    container_name: fastapi-app
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully


volumes:
  pg_data:
